site_name: Projeto Mercado - Anonna

theme:
    name: material
    logo: img/logo_projeto_mercado.png
    favicon: img/logo_projeto_mercado.png

markdown_extensions:
    - admonition  # Ativa os blocos de aviso (admonitions)
    - pymdownx.details # Necessário para que os admonitions possam ser recolhíveis (collapse)

features:
      # Use esta linha se você quiser ocultar a barra lateral automaticamente
      # quando não houver espaço suficiente (útil em telas menores)
      - toc.autohide 
      
      # Para ter controle total e garantir que o corpo principal seja mais largo, 
      # você pode remover todas as menções a 'toc' e apenas listar outros recursos
      # que você deseja manter (como navegação por abas, se ativado).
      
      # Exemplo SEGURO para manter a navegação principal (esquerda) e maximizar o conteúdo:
      - navigation.instant
      - navigation.tracking
      - search.suggest
      - search.highlight
      
    # ---------------------------------------------

extra_css:
    - css/extra.css

copyright: Copyright &copy; 2025 Projeto Anonna. Todos os direitos reservados.

extra:
    generator: false # Remove a frase "Made with Material for MkDocs"

nav: # Estrutura de navegação principal (menu lateral)
    - Home: index.md
    # 2. Página de Arquitetura (Inserir este bloco)
    - Arquitetura: 
        - Diagrama da Arquitetura: Arquitetura/arq.md
    - Telas do Projeto:
        - Tela Inicial: telas/tela-inicial.md
        - Tela de Busca: telas/tela-de-busca.md
        - Perfil: telas/perfil.md
    - API: API/api.md
